[Documentation:Submission] Added VCS Gradeable Type
Submitty/submitty.github.io pull request #430
Opened 2022-06-03 20:26 UTC by KaelanWillauer

Updates documentation on https://github.com/Submitty/Submitty/pull/7435

https://submitty.org/student/submission/version_control
![Screenshot from 2022-06-03 13-18-54](https://user-images.githubusercontent.com/49886320/171946672-b74246a7-34bf-47ac-8fe6-4c13c9c94555.png)

2023-07-13 02:49 UTC, bmcutler commented
@IDzyre Can you please update the documentation as necessary?
Thanks!

2023-08-08 19:31 UTC, NiaHeermance requested changes
Looks good! Just some small typo stuff to fix and I'll approve it.

2023-08-08 19:31 UTC, NiaHeermance commented on _docs/instructor/assignment_preparation/submission_version_control.md
> +type the SSH clone link, but replace your user id with {$user_id} `Should look like git@github.com:{$user_id}/student101.git`
Typo: `with {$user_id}.` (Should have period.)

2023-08-08 19:31 UTC, NiaHeermance commented on _docs/instructor/assignment_preparation/submission_version_control.md
> +__NOTE: Students user ids in Submitty need to be the same as your VCS system__
Probably should have period. `as your VCS system.`

2023-08-08 19:31 UTC, NiaHeermance commented on _docs/instructor/assignment_preparation/submission_version_control.md
> +1. Create a group/organization with a simple name (e.g. cptr101. This part can be skipped if using the instructors repositories.)
Typo: I'm assuming you meant `instructor's repositories`?

2023-08-08 19:31 UTC, NiaHeermance commented on _docs/student/submission/version_control.md
> +4. To pull changes from the upstream repository, use the commands
Maybe do `user the commands:` instead, adding a colon.

2023-08-09 17:38 UTC, IDzyre approved these changes

2023-08-10 16:24 UTC, merged