[Documentation:Developer] Update cypress docs with 10x version
Submitty/submitty.github.io pull request #463
Opened 2022-10-05 03:44 UTC by shailpatels

When we upgraded to Cypress 10x in the PR https://github.com/Submitty/Submitty/pull/8306 the UI for the cypres app was updated and some of the links and file structures that are in our docs no longer represent the current version.

This PR updates the cypress testing page and it also removes some images of the UI and replaces them with links to the cypress documentation so we don't have to keep maintaining it.

2022-10-05 12:29 UTC, shivam-sharma7 requested changes

2022-10-05 12:29 UTC, shivam-sharma7 commented on _docs/developer/testing/cypress.md
```suggestion

```
remove extra line.

2022-10-05 13:28 UTC, shivam-sharma7 commented
Okay 👍

On Wed, Oct 5, 2022, 18:56 Shail Patel ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In _docs/developer/testing/cypress.md
> <https://github.com/Submitty/submitty.github.io/pull/463#discussion_r987921114>
> :
>
> > @@ -168,7 +170,7 @@ cy.get('my_element')
>  });
>  ```
>
> -This prevents code from being executed if a previous part of the chain fails, see more about it [here](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous)
> +This prevents code from being executed if a previous part of the chain fails, [see more about it here](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous)
>
>  ### Debugging
>
>
> The extra line is intentional, it adds a space between text in markdown so
> the link is more visible
>
> https://gist.github.com/shaunlebron/746476e6e7a4d698b373
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Submitty/submitty.github.io/pull/463#discussion_r987921114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZPEUZ6ZH7HHS3M5T7ROTLWBV6YFANCNFSM6AAAAAAQ5FDJMY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-06 00:55 UTC, shivam-sharma7 approved these changes
lgthm 👌

2022-10-09 14:02 UTC, MasterOdin approved these changes

2022-10-09 14:02 UTC, merged