VPN- Error
Submitty/submitty.github.io pull request #510
Opened 2023-06-05 10:18 UTC by musaabimran

This is the Error that occurs with people outside USA.

2023-06-13 10:50 UTC, musaabimran commented
> I don't think you meant to delete the bundle config file & gemfile lock file. Please review the edits with this PR.
> 
> Also, I don't think the instructions to run 'vagrant provision' are useful in the general case.

Yes we don't have to delete bundle config file & gemfile lock file. And I have replaced the 'vagrant provision' with 'vagrant up'

2023-07-13 18:47 UTC, bmcutler commented
@musaabimran 

When I view 'files changed', I still see that you have edited unnecessary files in this PR

![Screenshot 2023-07-13 at 2 47 19 PM](https://github.com/Submitty/submitty.github.io/assets/5871417/da9a225d-f920-4407-b56a-8bb5c601c411)

2023-07-13 18:48 UTC, bmcutler requested changes
see note above

2023-07-14 14:29 UTC, bmcutler approved these changes

2023-07-14 14:29 UTC, merged