[Documentation:Developer] Reorganize troubleshooting
Submitty/submitty.github.io pull request #565
Opened 2023-11-12 20:31 UTC by RitaLei123

Reorganized the troubleshooting pages under developer. Organized troubleshooting into 3 files (Installation troubleshooting, Re-installation troubleshooting, and System Clock Testing & Troubleshooting). Now developers can go to the new troubleshooting folder to find instructions on how to fix their problem.

2023-11-17 21:14 UTC, Nicc041 approved these changes
Everything works and the code looks good.

2023-11-28 17:45 UTC, benjaminlee755 reviewed
The code seems fine and works.

2023-12-01 20:40 UTC, bmcutler requested changes
suggested undoing some of the shuffling

2023-12-01 20:40 UTC, bmcutler commented on _docs/developer/development_instructions/index.md
> -## System Clock Testing & Troubleshooting
i agree with moving the system clock troubleshooting to another file

2023-12-01 20:40 UTC, bmcutler commented on _docs/developer/development_instructions/index.md
> -## System Re-Configuration
but the instructions for teting changes to configure_submitty.py & etc should stay here

2023-12-01 20:40 UTC, bmcutler commented on _docs/developer/development_instructions/index.md
> -## Re-Creating All Sample Course Data
and the instructions for rebuilding sample course data should stay here

2023-12-01 20:40 UTC, bmcutler commented on _docs/developer/development_instructions/index.md
> -## Complete System Re-Installation
and system re-installation instructions should stay here

2023-12-01 20:40 UTC, bmcutler commented on _docs/developer/development_instructions/sample_data.md
> +See also: [Re-Creating All Sample Course Data](/developer/troubleshooting/reinstallation_troubleshooting)
so we will revert this change

2023-12-01 20:40 UTC, bmcutler commented on _docs/developer/troubleshooting/reinstallation_troubleshooting.md
> +---
this shouldn't be a separate page, its not troubleshooting, they are development instructions (less commonly used, but still development instructions)

2023-12-01 20:40 UTC, bmcutler commented on navtreedata.js
> +                [ "Re-Installation", "/developer/troubleshooting/reinstallation_troubleshooting", null ],
I think this goes away

2023-12-12 21:06 UTC, bmcutler approved these changes

2023-12-12 21:06 UTC, merged