[Documentation:Markdown] Enhanced Markdown Documentation for Additional Features
Submitty/submitty.github.io pull request #573
Opened 2023-12-27 06:58 UTC by NareshBiradar1

Fixes https://github.com/Submitty/Submitty/issues/10072 , where the Markdown editor in Submitty lacked documentation for certain features, specifically tables. I have added comprehensive instructions on how to create tables in Markdown to enhance the documentation.

2024-01-18 00:05 UTC, PythonCoderAS requested changes
Just a few syntax corrections.

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +    For more Information , [Click here](https://www.markdownguide.org/extended-syntax/#tables)
```suggestion
    For more information, [click here](https://www.markdownguide.org/extended-syntax/#tables)
```

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +
```suggestion

    There are also several tools online that can aid with creating a markdown table, such as [this tool](https://tableconvert.com/markdown-generator).
```

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +    ```
```suggestion
    ```markdown
```

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +    To add a table, use three or more hyphens (---) to create each column’s header, and use pipes (|) to separate each column. For compatibility, you should also add a pipe on either end of the row.
```suggestion
```

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +    To add a table, use three or more hyphens (---) to create each column’s header, and use pipes (|) to separate each column. For compatibility, you should also add a pipe on either end of the row.
Duplicated text?

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +
```suggestion
```

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +
```suggestion
```

2024-01-18 00:05 UTC, PythonCoderAS commented on _docs/student/communication/markdown.md
> +    ```
```suggestion
    ```
    The resulting table would look like this:
    | Syntax      | Description |
    | ----------- | ----------- |
    | Header      | Title       |
    | Paragraph   | Text        |
```

2024-06-05 15:46 UTC, bmcutler approved these changes

2024-06-05 15:46 UTC, merged